### ISSUE TITLE
Module is broken in 4.11 on

### ISSUE THREAD

**Issue by pieper** [Slicer/LandmarkRegistration#29]
The module became broken as a result of chnages to the Slicer Markups module and needs to be ported.  This has led to some confusion (e.g. https://discourse.slicer.org/t/how-to-load-landmarks/10127/11) so it should be disabled until there is time to fix it.

See also:
https://issues.slicer.org/view.php?id=2579
https://issues.slicer.org/view.php?id=3582
https://issues.slicer.org/view.php?id=3553

**Comment by Sunderlandkyl** [comment]
Fixed in 3a54203, and re-enabled in https://github.com/Slicer/Slicer/commit/3987c758f59e5cc70b645d05d4db890e8b0202d1
